FROM tensorflow/tensorflow:1.12.0-py3

ENV LANG=C.UTF-8
RUN apt-get clean \
    && apt-get -y update
RUN apt-get -y install nginx \
    && apt-get -y install python3-dev \
    && apt-get -y install build-essential

RUN mkdir /gpt_de_assis
ADD ./gpt_de_assis/ /gpt_de_assis/
WORKDIR /gpt_de_assis

RUN pip3 install -r requirements.txt
COPY /gpt_de_assis/nginx.conf /etc/nginx
RUN chmod +x ./start.sh
CMD ["./start.sh"]
